name: CI

on: [push, pull_request]

jobs:
  industrial_ci:
    strategy:
      matrix:
        env:
          #- {ROS_DISTRO: melodic, ROS_REPO: testing}
          - {ROS_DISTRO: melodic, ROS_REPO: main}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: 'ros-industrial/industrial_ci@master'
        env: ${{matrix.env}}
      - uses: actions/checkout@v2

      - run: |
            ls

      #- run: echo hello > path/to/artifact/world.txt

      #- uses: actions/upload-artifact@v2
      #  with:
      #    name: my-artifact
      #    path: path/to/artifact/world.txt
          